### ISSUE TITLE
Error trying to download CaCTS

### ISSUE THREAD

**Issue by Namekir** [lawrenson-lab/CaCTS#5]
I ran option 2 to download CaCTS and I get this error:

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`lawrenson-lab`) and repo name (`CaCTS_pkg`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by Namekir** [comment]
It worked when I changed it to `install_github("lawrenson-lab/CaCTS")` - recommend updating the README :)

**Comment by mabraao** [comment]
Thanks!
